# Generated by Django 5.0.7 on 2024-10-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_studentlist'),
        ('facultyapp', '0006_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='MarksForm',
        ),
    ]
