# Generated by Django 5.0.7 on 2024-10-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_contact_studentlist_user'),
        ('facultyapp', '0007_rename_marks_marksform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarksForm',
            new_name='Marks',
        ),
    ]
